from app.models.clinic_model import Clinic
from app.models.patient_model import Patient
from app.models.professional_model import Professional
from app.models.professional_clinic_model import ProfessionalClinic
from app.models.patient_clinics_model import PatientClinic
from app.models.specialty_model import Specialty
from app.models.medical_specialty_model import ProfessionalSpecialty
from app.models.clinic_specialty_model import ClinicSpecialty
from app.models.appointment_model import Appointment
from app.models.schedule_availability_model import ScheduleAvailability
from app.models.user_model import User
from app.models.user_clinic_model import UserClinic
from app.models.role_model import Role
from app.models.permission_model import Permission
from app.models.user_role_model import UserRole
from app.models.role_permission_model import RolePermission
from app.models.insurance_model import Insurance
from app.models.insurance_plan_model import InsurancePlan
from app.models.plan_model import Plan
from app.models.patient_insurance_plan_model import PatientInsurancePlan
from app.models.patient_contacts_model import PatientContact