"""add schedule availability to appointments

Revision ID: 0647abec7932
Revises: 37b5f932db3a
Create Date: 2026-09-06 12:12:52.235939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0647abec7932'
down_revision: Union[str, Sequence[str], None] = '37b5f932db3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('schedule_availability_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'schedule_availabilities', ['schedule_availability_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'schedule_availability_id')
    # ### end Alembic commands ###
