"""add birth date to patients

Revision ID: 4806aec454fe
Revises: 3dce91a62490
Create Date: 2026-08-21 19:45:03.519045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4806aec454fe'
down_revision: Union[str, Sequence[str], None] = '3dce91a62490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('birth_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'birth_date')
    # ### end Alembic commands ###
