"""update entity insurance_plan_model insurance, plan and others

Revision ID: 78cec85b25b0
Revises: f603ac435298
Create Date: 2026-09-27 19:52:29.694214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cec85b25b0'
down_revision: Union[str, Sequence[str], None] = 'f603ac435298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'insurances', ['registration'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insurances', type_='unique')
    # ### end Alembic commands ###
