"""create patient_clinic_model_association

Revision ID: 9648c16ca3ee
Revises: e77fa800c1b4
Create Date: 2026-08-29 17:15:40.432676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9648c16ca3ee'
down_revision: Union[str, Sequence[str], None] = 'e77fa800c1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("patient_clinics",
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'clinic_id')
    )

    op.execute(
        sa.text(
            "INSERT INTO patient_clinics(patient_id, clinic_id) SELECT patients.id, patients.clinic_id FROM patients;"
        )
    )

    op.drop_constraint(op.f('fk_patients_clinic_id'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'clinic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'patients', 
            sa.Column(
                'clinic_id',
                sa.INTEGER(),
                autoincrement=False,
                nullable=True
            )
    )

    op.execute(
        sa.text(
            "UPDATE patients SET clinic_id = (SELECT clinic_id FROM patient_clinics WHERE patient_clinics.patient_id = patients.id LIMIT 1)"
        )
    )

    op.alter_column(
        'patients',
        'clinic_id',
        nullable=False
    )

    op.create_foreign_key(op.f('fk_patients_clinic_id'), 'patients', 'clinics', ['clinic_id'], ['id'])

    op.drop_table('patient_clinics')
    # ### end Alembic commands ###
