"""make snomed code unique

Revision ID: deb0300ead23
Revises: ea8a58837a42
Create Date: 2026-09-01 13:30:12.023073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb0300ead23'
down_revision: Union[str, Sequence[str], None] = 'ea8a58837a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialties', ['snomed_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialties', type_='unique')
    # ### end Alembic commands ###
