"""add specialties and specialty associations

Revision ID: ea8a58837a42
Revises: 9648c16ca3ee
Create Date: 2026-09-01 12:56:19.764446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8a58837a42'
down_revision: Union[str, Sequence[str], None] = '9648c16ca3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('alternative_name', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=False),
    sa.Column('snomed_code', sa.String(), nullable=False),
    sa.Column('medical_exercise', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_specialties',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('clinic_id', 'specialty_id')
    )
    op.create_table('professional_specialties',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('professional_id', 'specialty_id')
    )
    op.drop_column('professionals', 'specialty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('professional_specialties')
    op.drop_table('clinic_specialties')
    op.drop_table('specialties')
    # ### end Alembic commands ###
