from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database import get_db
from app.schemas.patient_contact_schema import PatientContactCreate, PatientContactResponse, PatientContactUpdate
from app.services.patient_contact_service import create_patient_contact, get_patient_contact, get_patient_contacts,update_patient_contact, delete_patient_contacts

from app.core.exceptions import PatientNotFoundError, PatientContactNotFoundException, PatientContactAlreadyExistsException